[package]
edition = "2021"
name = "web_app"
version = "0.1.0"

[dependencies]
api = { workspace = true, features = ["web_app"] }
ui = { workspace = true, features = ["web_app"] }

chrono = { workspace = true }
dioxus = { workspace = true, features = ["fullstack", "router"] }
dotenvy = { workspace = true, optional = true }
lucide-dioxus = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
wasm-bindgen = { workspace = true, optional = true }
web-sys = { workspace = true, optional = true }

[features]
default = []
server = ["dep:dotenvy", "ui/server"]
web = ["ui/web"]

# wasm optimizations
[profile.web-release]
codegen-units = 1
debug = false
incremental = false
lto = true
opt-level = "z"
panic = "abort"
strip = true
