[package]
edition = "2021"
name = "ui"
version = "0.1.0"

[dependencies]
api = { workspace = true, features = [
    "events",
    "mobile_app",
    "support",
    "surveys",
    "web_app",
] }

dioxus = { workspace = true }
gloo = { workspace = true, optional = true }
lucide-dioxus = { workspace = true }
wasm-bindgen = { workspace = true, optional = true }
web-sys = { workspace = true, optional = true }

[features]
events = []
marketing = []
mobile_app = []
server = ["api/server"]
support = []
surveys = []
web = ["dep:gloo", "dep:wasm-bindgen", "dep:web-sys", "dioxus/web"]
web_app = []
