[package]
edition = "2021"
name = "ui"
version = "0.1.0"

[dependencies]
api = { workspace = true, features = [
    "events",
    "mobile_app",
    "shared",
    "web_app",
] }
dioxus = { workspace = true }
gloo = { version = "0.11.0", optional = true }
lucide-dioxus = { version = "2.44.0", features = ["all-icons"] }
wasm-bindgen = { version = "0.2.105", optional = true }
web-sys = { version = "0.3.82", optional = true }

[features]
events = []
marketing = []
mobile_app = []
server = ["api/server"]
shared = []
web = ["dep:gloo", "dep:wasm-bindgen", "dep:web-sys", "dioxus/web"]
web_app = []
