[package]
edition = "2021"
name = "stop_communism"
version = "0.1.0"

[dependencies]
chrono = { version = "0.4" }
dioxus = { workspace = true, features = ["fullstack", "router"] }
gloo = { version = "0.11.0", optional = true }
lucide-dioxus = { version = "2.44.0", features = ["all-icons"] }
ui = { workspace = true, features = ["shared"] }
wasm-bindgen = { version = "0.2.105", optional = true }
web-sys = { version = "0.3.82", optional = true }

[features]
default = []
server = ["ui/server"]
web = ["ui/web"]

# Web optimized for size
[profile.web-release]
codegen-units = 1
debug = false
incremental = false
lto = true
opt-level = "z"
panic = "abort"
strip = true
