[package]
edition = "2021"
name = "stop_communism"
version = "0.1.0"

[dependencies]
ui = { workspace = true }

chrono = { workspace = true }
dioxus = { workspace = true, features = ["fullstack", "router"] }
gloo = { workspace = true, optional = true }
lucide-dioxus = { workspace = true }
wasm-bindgen = { workspace = true, optional = true }
web-sys = { workspace = true, optional = true }

[features]
default = []
server = ["ui/server"]
web = ["ui/web"]

# wasm optimizations
[profile.web-release]
codegen-units = 1
debug = false
incremental = false
lto = true
opt-level = "z"
panic = "abort"
strip = true
